### ISSUE TITLE
Angular direction for directions

### ISSUE THREAD

**Issue by pjanck** [buildingSMART-Finland/InfraModel#47]
https://github.com/buildingSMART-Finland/InfraModel/blob/6a218ccc9637ca7a3483531a89a35517ba7456ab/markdown/headers.md?plain=1#L46

Double checking: in geodesy, whenever North is the base direction and one measure angles from it, it is usually clock-wise. The sentence above states the opposite.

**Comment by mvesanen** [comment]
That's right... I have no clues why this is historically defined in this non-intuatitive way. Can't make change, this would broke all existing implementations.
