### ISSUE TITLE
Elliposid's attribute `inverseFlattening`

### ISSUE THREAD

**Issue by pjanck** [buildingSMART-Finland/InfraModel#49]
https://github.com/buildingSMART-Finland/InfraModel/blob/6a218ccc9637ca7a3483531a89a35517ba7456ab/markdown/headers.md?plain=1#L90

![grafik](https://github.com/buildingSMART-Finland/InfraModel/assets/59165496/c81bca16-8e69-453a-af72-c5640dda31f7)

I propose to change the description of the last attribute to "Ellipsoid inverse flattening".

**Comment by mvesanen** [comment]
https://github.com/buildingSMART-Finland/InfraModel/pull/60
