### ISSUE TITLE
Issue templates

### ISSUE THREAD

**Issue by pjanck** [buildingSMART-Finland/InfraModel#50]
While I commend the authors to provide three templates for issues, these aren't really explanatory to a non-Finnish speaker :D

![grafik](https://github.com/buildingSMART-Finland/InfraModel/assets/59165496/6e7f475e-a683-4bf7-9abc-11cb43ceb9ac)

Propose to at least add a description in English to them as well.

**Comment by mvesanen** [comment]
Issue types translated
