### ISSUE TITLE
Units of attributes of `im:TransverseMercator`

### ISSUE THREAD

**Issue by pjanck** [buildingSMART-Finland/InfraModel#54]
Similarly to #51:

![grafik](https://github.com/buildingSMART-Finland/InfraModel/assets/59165496/53b4cbd3-22a9-4c7a-83fa-9b9afb7b7441)

Only the last attribute is explicit about the unit. Propose to add this for all attributes.

**Comment by mvesanen** [comment]
https://github.com/buildingSMART-Finland/InfraModel/pull/60
