### ISSUE TITLE
Author of the file - one or many?

### ISSUE THREAD

**Issue by pjanck** [buildingSMART-Finland/InfraModel#56]
These seem contradictory:

![grafik](https://github.com/buildingSMART-Finland/InfraModel/assets/59165496/b1e26981-7623-4a02-bfcc-6eaf3ffff15e)

![grafik](https://github.com/buildingSMART-Finland/InfraModel/assets/59165496/493fa844-0290-42ae-968a-82026920558e)

**Comment by mvesanen** [comment]
https://github.com/buildingSMART-Finland/InfraModel/pull/60
