### ISSUE TITLE
`im:Source` documentation

### ISSUE THREAD

**Issue by pjanck** [buildingSMART-Finland/InfraModel#58]
`im:Source` documentation speaks of Date and Type:

![grafik](https://github.com/buildingSMART-Finland/InfraModel/assets/59165496/5f3c609d-b1a9-461e-8f74-ce8cec2cecc3)

while its use in `im:DataQuality` of "when and where"

![grafik](https://github.com/buildingSMART-Finland/InfraModel/assets/59165496/dddefa10-4b10-468b-828b-e10c837373ac)

I understand the pair *when - Date*, however have difficulties seeing the connection *where - Type*. Is this intentional?

**Comment by mvesanen** [comment]
https://github.com/buildingSMART-Finland/InfraModel/pull/60
