### ISSUE TITLE
`im:ModelStatus` attributes' optionality

### ISSUE THREAD

**Issue by pjanck** [buildingSMART-Finland/InfraModel#59]
`im:ModelStatus` is optional in itself and has all optional attributes.

![grafik](https://github.com/buildingSMART-Finland/InfraModel/assets/59165496/643456d4-bc50-4197-ace6-c441471c1a7a)

![grafik](https://github.com/buildingSMART-Finland/InfraModel/assets/59165496/c6732e5a-cb4a-4abd-9edd-e8d1e905415a)

What does it mean, if the element is provided, but it is empty? E.g `<im:ModelStatus />`?

**Comment by mvesanen** [comment]
Yes, it means that the im:ModelStatus element could be empty. Thisreally doesn't broke anything, so i will let it be as it is.
