### ISSUE TITLE
IMPipeNetworkMaterialType, teräsaaltolevy puuttuu enumeraatiolistasta

### ISSUE THREAD

**Issue by mvesanen** [buildingSMART-Finland/InfraModel#63]
**Virheen kuvaus**
IMPipeNetworkMaterialType, teräsaaltolevy puuttuu

**Ehdotus virheen korjaamiseksi**
Lisätään "corrugated plate"/"corrugated iron"/"waveplate" --> IMPipeNetworkMaterialType

**Kuvakaappauksia**
Lisää tarvittaessa kuvakaappauksia ongelmasi selittämiseksi.

**Mahdollinen lisätieto**
Lisää tähän mikä tahansa muu ongelmaan liittyvä tieto.

**Raportoijan yhteystiedot**
mvesanen

**Comment by JuhaHy** [comment]
Onko tämä materiaali, vai paremminkin tyyppi-/profiilitieto? Jos lisätään materiaaliksi, pitää selventää thichness-attribuutin merkitys: materiaalivahvuus vai profiilin korkeus? Struct-kuvista saisi nyt käsityksen, että jälkimmäinen.

**Comment by mvesanen** [comment]
Lisätään optionaalinen IMPipeNetworkMaterialProfile attribuutti kaivoille ja putkille jolla enumeraatio (flat,corrugated,other) koska myös muoviset ryppyputket puuttuu

**Comment by jarikainuvaara** [comment]
Tämä tehty myös
