### ISSUE TITLE
IM_RoadSign "sizeDesignation" tarkempi määritelmä

### ISSUE THREAD

**Issue by mvesanen** [buildingSMART-Finland/InfraModel#65]
**Liittyykö kysymys esim. ongelmaan, dokumentaatioon, skeemaan, ohjeistukseen? Kuvaile.**
Mikä on tarkempi määritelmä sizeDesignationille "Small/Regular/Large"?

**Kuvaile vaihtoehtoja, joita olet harkinnut**
Selkeä ja ytimekäs kuvaus kaikista harkitsemistasi vaihtoehtoisista ratkaisuista tai ominaisuuksista.

**Kuvakaappauksia**
Lisää tarvittaessa kuvakaappauksia asian selittämiseksi.

**Mahdollinen lisätieto**
Lisää tähän mikä tahansa muu asiaan liittyvä tieto.

**Raportoijan yhteystiedot**
ppalviainen

**Comment by mvesanen** [comment]
Selvitetään mikä on oikea yksikkö tai enumeraatiojoukko (velhosta?) ja korjataan skeeman selite ja tietotyyppi

**Comment by jarikainuvaara** [comment]
Velhon tietotyypit ja määritelmät: https://ohje.velho.vaylapilvi.fi/wp-content/uploads/2023/05/TR_Velho_Vastaavuustaulukko_08052023.pdf

Ei avata tarkemmin kokojen merkitystä tai mittakaavoja. Eli paras tieto on pieni, normaali ja iso.

**Comment by jarikainuvaara** [comment]
https://ava.vaylapilvi.fi/ava/Julkaisut/Vaylavirasto/vo_2023-29_liikennemerkkien_kaytto_web.pdf 
 
2.3 Liikennemerkkien koko
 
Liikennemerkkejä on kolmea kokoa: suurikokoisia, normaalikokoisia ja pienikokoisia. Yleensä käytetään normaalikokoisia liikennemerkkejä. Pienikokoisia liikennemerkkejä voidaan käyttää poikkeuksellisesti taajamissa, nopeusrajoituksen ollessa alle 40 km/h. Suurikokoisia liikennemerkkejä voidaan käyttää moottori - ja moottoriliikennetiellä sekä niihin liittyvillä tietyömailla. Merkkejä voidaan käyttää mm. lähestyttäessä moottori- ja moottoriliikennetien päättymiskohtaa tai tietöiden alkamiskohtaa, jolloinnopeuspieneneeportaittainjaajokaistajärjestelyt ovat normaalista poikkeavat tai ajokaistojen määrä pienenee. Muuten moottori- ja moottoriliikenneteillä ja niiden tietyömailla liikennemerkit ovat yleensä normaalikokoisia. Muilla teillä suurikokoisia merkkejä voidaan käyttää tietyön yhteydessä samoin edellytyksin kuin moottori- ja moottoriliikenneteillä tienkohdassa, jossa suurin sallittu nopeus on 80 km/h tai suurempi. Liikenne - ja viestintävirasto on laatinut kaikista tieliikennelain mukaisista liikennemerkeistä mitoituspiirustukset, jotka ovat määräyksen Liikenteenohjauslaitteiden värit, rakenne ja mitoitus liitteenä. Liikenne - ja viestintäviraston määräykses - s ä mainittujen kokojen lisäksi voidaan käyttää merkkiä C1 (ajoneuvolla ajo kielletty) pienoiskokoisena, 200 mm:n tai 400 mm:n läpimittaisena, liikenteen valvojan tai ohjaajan antamana merkkinä.
 
Ja ettei homma olisi liian helppoa, niin Traficomilla ohjeistetaan liikenteenohjauslaitteiden värit, rakenne ja mitoitus

https://www.traficom.fi/fi/liikenne/liikennejarjestelma/liikenteenohjauslaitteiden-varit-rakenne-ja-mitoitus?toggle=Liikenteenohjauslaitteiden%20v%C3%A4rit%2C%20rakenne%20ja%20mitoitus

Liikenteenohjauslaitteiden värit, rakenne ja mitoitus | Traficom
Tieliikennelain mukaiset määräykset liikenteenohjauslaitteiden väreistä, rakenteesta ja mitoituksesta.
 
Ja liitteissä merkkiryhmittäin sitten tarkempi mitoitus eri asioille.. Esimerkkinä tämä 

https://www.traficom.fi/sites/default/files/media/regulation/Liite_3_Tieliikennelain_merkkiryhman_B_liikennemerkkien_mitoitus_2022_3.pdf

**Comment by jarikainuvaara** [comment]
Lisättiin enumeraatioon ja selitteet
