### ISSUE TITLE
IM_structLayer, selitteet eri alielementeille

### ISSUE THREAD

**Issue by mvesanen** [buildingSMART-Finland/InfraModel#68]
** Liittyykö kehitysideasi ongelmaan? Kuvaile.**
Mitä tarkoittaa seuraavat:
- pavementType
- surfacingMethod
- stoneStructureType
- stoneType
- lightweightFillMaterialProperty
Vanhoista IM dokumentaatioista joutuu kaivamaan vastauksia...

**Kuvaile haluamasi ratkaisu**
Lisätään selitteet ja käyttötapaukset tekstinä.

**Kuvaile vaihtoehtoja, joita olet harkinnut**
Selkeä ja ytimekäs kuvaus kaikista harkitsemistasi vaihtoehtoisista ratkaisuista tai ominaisuuksista.

**Kuvakaappauksia**
Lisää tarvittaessa kuvakaappauksia asian selittämiseksi.

**Mahdollinen lisätieto**
Lisää tähän mikä tahansa muu asiaan liittyvä tieto.

**Raportoijan yhteystiedot**
Kehitysidean antajan yhteystiedot lisätietojen saamiseksi

**Comment by mvesanen** [comment]
Selvitetään projektin työlistalta mistä nämä oli kotoisin ja mitä nämä oikeasti tarkoittaa.
Lisätään järkevät selitteet skeemaan josta ne sitten päätyy taulukkoon.

**Comment by jarikainuvaara** [comment]
lightweightFillMaterialProperty lienee meidän typo aiemmasta projektista. -> otetaan pois, jos tätä joku tarvitsee niin userDefinedProperties pelastaa.

lightweightFillMaterial on ok ja tällä kuvataan kevennykseen käytetty materiaali kuten kevytsora, vaahtolasi tms.

stoneStructureType -> ei tämä nyt kyllä selvitä, stoneType ihan selkeä, mutta tämä on hankala
ladontaan esimerkkejä täältä -> https://www.netrauta.fi/attachments/products/benders/laatat-kivet/ladontamalleja.pdf 

Historiaa kaiveltuna, ovat molemmat olleet pidempään skeemassa tai enumeraatioissa roikkumassa.

@mvesanen hieroo muutoksia dokumentaatioon ja skeemaan
