### ISSUE TITLE
XML example of <LandXML>

### ISSUE THREAD

**Issue by JuhaHy** [buildingSMART-Finland/InfraModel#72]
** Liittyykö kehitysideasi ongelmaan? Kuvaile.**
Inframodel 4.1 dokumentaatiossa oleva lyhyt esimerkki LandXML-tiedoston rakenteesta ei sisällä kaikkia elementtejä joita Inframodel-tiedonsiirrossa voi esiintyä (im-laajennusskeemasta).

**Kuvaile haluamasi ratkaisu**
Lisätään esimerkkiin 
 <im:LocalCoordinateTransformation>
 <im:Metadata>
 <im:PileGroups> 

Lisätään myös namespace ja schemaLocation -määrittelyt

**Comment by mvesanen** [comment]
Muutetaan "koneellisesti luotu" esimerkki käsin tehdyksi yllä olevan kuvauksen mukaan
