### ISSUE TITLE
XML example of <Project> - IM_codings label-arvoissa korjaamista

### ISSUE THREAD

**Issue by JuhaHy** [buildingSMART-Finland/InfraModel#73]
**Virheen kuvaus**
Esimerkissä
"terrainCodingSourceRef" tuplana (toinen po "terrainCodingDesc")
"surfaceCoding" tuplana (toinen po "surfaceCodingDesc")

**Ehdotus virheen korjaamiseksi**
Korjataan esimerkin virheelliset label-arvot

**Comment by mvesanen** [comment]
Korjataan esimerkin virheelliset label-arvot
