### ISSUE TITLE
Ground layer model dokumentaatio

### ISSUE THREAD

**Issue by JuhaHy** [buildingSMART-Finland/InfraModel#74]
**Virheen kuvaus**
Dokumentaatiossa sanotaan:
"The technical properties of each soil layer between two surfaces may be given in “IM_soil” extension described above."
Tämä (described above) ei enää päde, koska kyseisen Featuren kuvaus on nykysisin eri paikassa.

**Ehdotus virheen korjaamiseksi**
Päivitetään viittaus “IM_soil” extension -kuvaukseen.

**Comment by jarikainuvaara** [comment]
Markdowniin tekstimuutos. Mikko tekee

**Comment by jarikainuvaara** [comment]
Korjaillaan useampikin vastaava viittausvirhe jiiriin tässä samalla. @mvesanen työstää
