### ISSUE TITLE
IM_struct equipmentDesc

### ISSUE THREAD

**Issue by JuhaHy** [buildingSMART-Finland/InfraModel#75]
**Virheen kuvaus**
IM_struct Featuren dokumentaatiossa <equipmentDesc-ltProperty>>  kun pitäisi olla equipmentDesc <Property>
Skeemassa tämä puuttuu IM_structLabelType arvojen joukosta, sen sijaan sinne on tullut <xs:element name="equipmentDesc-ltProperty--gt"> ...

**Ehdotus virheen korjaamiseksi**
inframodel-raw.xsd korjattava <xs:element ref="equipmentDesc-ltProperty--gt" minOccurs="0"/>

**Comment by mvesanen** [comment]
Korjataan skeemaan. "-ltproperty--gt" --> "--ltproperty--gt"
Korjataan description Equiment-->Equipment
