### ISSUE TITLE
Boundaries, Breaklines, Breakline: ylimääräinen <xs:any namespace="##local"/>

### ISSUE THREAD

**Issue by JuhaHy** [buildingSMART-Finland/InfraModel#78]
**Virheen kuvaus**
LandXML 1.2 ei tunne elementeille Boundaries, Breaklines tai Breakline alielementtiä <xs:any namespace="##local"/>
Boundaries ja Breaklines elmenteiltä puuttuu Feature.

**Ehdotus virheen korjaamiseksi**
Poistetaan ylimääräiset, lisätään puuttuvat.

**Comment by mvesanen** [comment]
-UserDefinedproperties fearure tarvii lisätä Boundaries ja Breaklines. 
-Käydään läpi että kaikilla muillakin elementellä skeemassa.
-Poistetaan ylimääräiset ##local
