### ISSUE TITLE
LandXML, CoordinateSystem, PipeNetwork, Surface, DataPoints: ylimääräinen attribuutti <xs:anyAttribute namespace="##any"/>

### ISSUE THREAD

**Issue by JuhaHy** [buildingSMART-Finland/InfraModel#79]
**Virheen kuvaus**
LandXML 1.2 ei tunne näille elementeille attribuuttia <xs:anyAttribute namespace="##any"/>

**Ehdotus virheen korjaamiseksi**
Ylimääräiset pois.

**Comment by mvesanen** [comment]
Poistetaan ylimääräiset
