### ISSUE TITLE
Käyttöohjeessa päivitettävä name-kentän sallitut merkit

### ISSUE THREAD

**Issue by JuhaHy** [buildingSMART-Finland/InfraModel#85]
Ohjeen kohdan15.3.2.1 lopussa sanotaan "Tiedoston ja objektin nimi ei saa sisältää välilyöntejä, erikois- tai skandinaavisia merkkejä."
Objektien name-kentässä kuitenkin välilyönti on nyt sallittu.

**Comment by jarikainuvaara** [comment]
Tämä katsottiin skeemaan, mutta käyttöohjeeseen ei vielä puututtu. Korjataan sama teksti käyttöohjeen puolelle. Muutetaan teksti: poistetaan välilyönnit niin se on siinä.

**Comment by jarikainuvaara** [comment]
@mikko työstää tämän jiiriin
